### ISSUE TITLE
What should the URLs in the /links endpoint point to?

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/providers#27]
This does not seem to be an index meta-db as is required (which is also the case for @ml-evs's `odbx` server).
Since it's better with something instead of nothing, it's fine for me, but since we are explicitly requiring an index meta-db in the spec for this `providers.json`, we should at some point be a bit more clear cut. Maybe when `v1` is released?

_Originally posted by @CasperWA in https://github.com/Materials-Consortia/providers/pull/23_

In the first sentence of the description of this providers index meta-database, it's stated that it serves URLs to "the index databases of all OPTIMADE database providers that participate ...".
This I interpret as it should list URLs to OPTIMADE index meta-databases (see [definition](https://github.com/Materials-Consortia/OPTIMADE/blob/develop/optimade.rst#index-meta-database)) and not fully-fledged OPTIMADE servers.

Materials Cloud has the use case of serving many different OPTIMADE databases, and as such the means to have a single URL representing the collection of these, is important.
For a use case of a provider serving only a single DB, an index-meta database can be easily served with static files (this repo is the evidence of this in and of itself).

However, it seems there is some confusion as to what the URLs should point to, hence I am opening this issue to discuss this.

Since this is particular to Materials-Consortia and not the OPTIMADE API specification, the issue is opened in _this_ repository, instead of under the OPTIMADE repository.

**Comment by CasperWA** [comment]
Tagging @blokhin @shyamd @rartino @giovannipizzi @ml-evs @fekad @ltalirz

**Comment by blokhin** [comment]
My approach with the [Sky-Scanner app](https://optimade.science) is as follows:

- download the [most actual providers list](https://providers.optimade.org/src/links/v1/providers.json),
- iterate it and discard the providers with the empty `base_url` 😢
- contact the `/info` endpoints for the rest and check if the `structures` endpoint is present in the `available_endpoints`,
- if yes, enable a provider for querying and re-direct all the user's queries to the respective `structures` endpoint

Am I missing something?

**Comment by ml-evs** [comment]
> Am I missing something?

The `base_url` listed here can either correspond to a specific database (that e.g. has `/structures`, a `parent`), or to an index meta-db that provides `/links` for all the `child` databases of that implementation, which is the case for e.g. https://dev-aiida-dev.materialscloud.org/optimade/v0/links. If you crawl over those URLs you should get lots of possible `/structures` endpoints for the skyscanner!

What @CasperWA wants to do is force all `base_url`s listed here to point to only index meta-dbs, or at least clarify this in the specification.

**Comment by rartino** [comment]
Here is a comment I wrote about where this requirement comes from and a bit of motivation: https://github.com/Materials-Consortia/providers/pull/23#discussion_r420956122
(Feel free to look over also the rest of that discussion in issue #23)

**Comment by blokhin** [comment]
Thanks, now I see. From a consumer standpoint, I'd be strictly **against** such multi-level providers layout and such a fragmented federation. Could a provider always expose a **master** (or **parent**) endpoint or it is too idealistic and organizationally unfeasible?

**Comment by ml-evs** [comment]
> Thanks, now I see. From a consumer standpoint, I'd be strictly **against** such multi-level providers layout and such a fragmented federation. Could a provider always expose a **master** (or **parent**) endpoint or it is too idealistic and organizationally unfeasible?

I think that this is exactly what the index meta-db is intended for!

**Comment by CasperWA** [comment]
@blokhin So your approach would instead look something like:

> * download the [most actual providers list](https://providers.optimade.org/src/links/v1/providers.json),
> * iterate it and discard the providers with the empty `base_url` 😢
* contact the ~`/info`~ `/links` endpoints for the provider's databases and check if the `structures` endpoint is present in the linked databases.
> * if yes, enable a provider for querying and re-direct all the user's queries to the respective `structures` endpoint
> 
> Am I missing something?

Nope. Not with this setup.

However, beware, since some providers may sport _many_ databases, hence flooding your client. For these an extra level of "choosing the databases to search in" would be favorable (and kinder to the cables). A "catch-'em-all" solution is of course still available to boot.

**Comment by blokhin** [comment]
- How many levels of the sub-databases could there be?
- Could we end up with the closed loops (endless recursions) in the sub-databases?
- Why have you refused of one-level flat hierarchy of the providers list? Too hard to maintain?

**Comment by rartino** [comment]
I think this discussion is picking up on an interesting limitation of our current provider setup for @blokhin's application. Do we need some form of tag in /links to indicate which sub-databases a database provider think it makes sense to query in an aggregated search?

Because with the present setup, the aggregated search will query all my 42 test databases with nonsense data alongside my one production database.

@blokhin regarding your first two questions, I think the specification recommends only doing: index meta-database + a single level. For databases with more levels, I would suggest not trying to crawl them since they are doing something odd. 

For your last question (if I understand it correctly): the comment I linked (https://github.com/Materials-Consortia/providers/pull/23#discussion_r420956122) contains what I believe is the main motivation for refusing to link real databases directly from the central providers list.

**Comment by ltalirz** [comment]
> Do we need some form of tag in /links to indicate which sub-databases a database provider think it makes sense to query in an aggregated search?
> Because with the present setup, the aggregated search will query all my 42 test databases with nonsense data alongside my one production database.

Another simple way of solving this: only list production databases in the instance of the officially registered index metadatabase.

**Comment by CasperWA** [comment]
> > Do we need some form of tag in /links to indicate which sub-databases a database provider think it makes sense to query in an aggregated search?
> > Because with the present setup, the aggregated search will query all my 42 test databases with nonsense data alongside my one production database.
> 
> Another simple way of solving this: only list production databases in the instance of the officially registered index metadatabase.
> If you need another index of test databases, simply serve that under a different URL.

However, if it becomes an issue for the provider to want to host several index meta-databases for "reasons", then a simple `environment` property or similar would be useful to distinguish `production` from `development` or similar.

**Comment by rartino** [comment]
> However, if it becomes an issue for the provider to want to host several index meta-databases for "reasons", then a simple environment property or similar would be useful to distinguish production from development or custom ...

Still, rather than assume that the database provider wants all "production" databases queried in aggregated searches, I would prefer if there was a specific flag for this. I can see other reasons to opt some databases out of aggregated searches beyond "this isn't production data".

**Comment by CasperWA** [comment]
Can we reference (or copy over) the discussion/results from the discussion at the CECAM 2020 meeting here? (Tagging @rartino, since he was moderator of the session.)

**Comment by CasperWA** [comment]
*Taken from OneNote Notebook for Room 1 at the CECAM 2020 meeting, as the written documentation of an oral discussion on Tuesday 09.06.2020*:

**Discussion about the two-level requirement in providers#27**

Giovanni argues that it Is important with the two-level structure so that people don't accidentally just scan over those that have data at the first level.

After some discussion there seems to be an agreement to adopt the policy that two-level is enforced in the OPTIMADE providers list.

We should add a flag to opt-out of aggregated searches. Discussion about whether this is the same thing as database 'status' ~ 'production', 'test', 'staging'.

Giovanni: to be still discussed tomorrrow – 1) how to enforce this: do we set a deadline for people to fix their entry in the providers.json? 1 Aug 2020? Another date? 2) How do we document the checks that a reviewer needs to do before a merge of a PR in the providers repo?

**Comment by blokhin** [comment]
>two-level is enforced

Any reservation for the first-level-only providers (e.g. nomad, odbx, mpds)?

**Comment by blokhin** [comment]
cf. https://github.com/Materials-Consortia/providers/pull/29

**Comment by rartino** [comment]
And today at the OPTIMADE 2020 workshop we agreed that links that presently do not point to Index Meta-DBs should be "converted" to Index Meta-DB links internally hosted by the providers repository.

**Comment by giovannipizzi** [comment]
@blokhin just FYI (probably you know), for the top-level-only DBs, they will provide a `default` relationship (see [OPTIMADE specs](https://github.com/Materials-Consortia/OPTIMADE/blob/678a8bc329d88e2f187992bba46483f4921d57fc/optimade.rst#base-info-endpoint)) so you might want to use that field in your client app, if you wish.

**Comment by rartino** [comment]
@CasperWA, @giovannipizzi we can now close this?, right?

**Comment by CasperWA** [comment]
At the moment, it is stated it will be closed by #34, which is still open.
However, I have lost the overview of whether this particular issue was indeed resolved by another PR or discussion.

**Comment by blokhin** [comment]
Let's close it after https://github.com/Materials-Consortia/providers/pull/34 is closed?
