### ISSUE TITLE
Removal of the "Cambridge" provider

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/providers#3]
There was a discussion on a subset of the mailing list regarding the "Cambridge" provider. I believe this to now be defunct, but @gjc29 , @ajm143 and @fekad should probably confirm this before any change is made.

**Comment by ml-evs** [comment]
From offline discussion I think it's clear that this provider should be removed. Unless anyone disagrees in the next couple of days, I'll make a PR removing it.

**Comment by gjc29** [comment]
Yes, I concur that the Cambridge provider should be removed.
