### ISSUE TITLE
Providers: centralized (first-level-only) and decentralized (multi-level)

### ISSUE THREAD

**Issue by blokhin** [Materials-Consortia/providers#31]
Dear colleagues,

on the index meta-dbs in the providers list:

the providers may differ considerably in their organizational structure and how many optimade instances they provide (100, 3, or only one).

Would it make sense to accommodate that in the curated providers list format?

**Comment by giovannipizzi** [comment]
Hi @blokhin what do you mean exactly with `accomodate`?

**Comment by blokhin** [comment]
@giovannipizzi so a provider can omit serving the `index meta-db`, if he wants.
Instead, the `index meta-db` can be served by the [providers list](https://providers.optimade.org), correct?

**Comment by giovannipizzi** [comment]
Yes, this is our current approach, that is being implemented in #34. So we don't put additional requirements on implementers, but we make sure that the providers list always points to an index meta-db.

**Comment by blokhin** [comment]
I still believe that _forcing_ the `index meta-dbs` is non-elegant and over-complicated solution, especially for the future new members, but I appreciate the providers list is ready for the mitigation 👍
