### ISSUE TITLE
Add validation

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/providers#5]
We to implement at least some rudimentary validation of the providers.json file. Preferably with a travis check, so that we never will merge anything that breaks the file (that would be bad...)

**Comment by CasperWA** [comment]
I'll just repeat my other comment here, to continue discussion in this issue:

> (...) Is there a reason this repo doesn't need reviews before merging? I'd be worried about e.g. missing a comma in my own PR...

This is already an issue (#5).
Maybe we could use our validator from `optimade-python-tools`?
