### ISSUE TITLE
/versions missing expected header

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/providers#58]
This was spotted in PR #57 where the OPTIMADE validator is introduced to validate this implementation: https://github.com/Materials-Consortia/providers/pull/57/checks?check_run_id=1681301240#step:3:58

It simply states that we need to ensure we have the expected header for the `versions`-endpoints. This is also a hard requirement from the specification.

**Comment by rartino** [comment]
As far as I can see, the complaint in the validator is not that the header is missing (and it is not, the first line in the csv is 'version'), but it is that the content-type doesn't use a content-type parameter to declare the presence or not of the header. I don't think using that content-type parameter is a hard requirement. Can you give a citation on what you are reading that makes that a MUST-level requirement?

**Comment by CasperWA** [comment]
You're right, `header=present` just needs to be part of the header "content-type". It's stated in [section 5.2](https://github.com/Materials-Consortia/OPTIMADE/blob/develop/optimade.rst#versions-endpoint) of the specification. However, it's not clear cut that it's a requirement. Although it reads as an implicit hard requirement of how the endpoint's header "content-type" should be set up?

**Comment by CasperWA** [comment]
Actually, looking through the setup in this repository, there shouldn't be a response for `/v1/versions`, which is where the error is coming from. Hence the validator is wrong in validating this endpoint at this point.
It seems it validates `/versions` fine (unversioned base URL).

I'll open a new issue in OPTIMADE Python tools for this issue.

**Comment by rartino** [comment]
Section 5.2 only specifies that what is returned is a subset of the MIME type described by `text/csv; header=present`, I don't see anything I would specifically read as a formal requirement on the content-type parameter in the http headers. The CSV RFC does have a **lowercase** "should" when discussing the header, and other parts seem to suggest the content-type parameter is optional.

**Comment by rartino** [comment]
I get a 404 when requesting https://providers.optimade.org/v1/versions

So, can we close this bug?

**Comment by CasperWA** [comment]
> I get a 404 when requesting https://providers.optimade.org/v1/versions
> 
> So, can we close this bug?

Yes. This is a bug in the validator. I have just opened Materials-Consortia/optimade-python-tools#668 to track this.
