### ISSUE TITLE
Add CODEOWNERS

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/providers#60]
We should add a CODEOWNERS file to this repository; new implementations will not know who to ping for review, so PRs will sit here and stagnate without notifying anyone. 

I will make the PR for this next week unless there is a huge disagreement; I "volunteer" myself, @CasperWA and @merkys for now, but if you are reading this and interested, please comment too.

**Comment by merkys** [comment]
I am fine with being "volunteered" :) By the way, are there any requirements for PR acceptance besides the formal ones listed in README.md? If not, this role should be quite transparent: all additions are accepted, and modifications should be preferably approved by the developers of an implementation.

**Comment by ml-evs** [comment]
I agree, just follow the guidelines and make it clear that we can host index meta-databases too. We my want to adjust these guidelines in the next meeting, potentially only allowing people to provide a `base_url` once their implementation is actually live (but allowing "reservations" with `base_url: null` until then) just in case the domain name is not even owned yet... this will allow us to push a lot of other things into validation (e.g. checking dead links).

I will improve the validation over at https://github.com/Materials-Consortia/optimade-python-tools/issues/723 so we won't need to spot e.g. prefix issues as @CasperWA found.
