### ISSUE TITLE
Better 404 pages/redirection for static index meta-databases

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/providers#76]
It would be good to have a better default 404 template, such that when someone visits e.g. http://providers.optimade.org/index-metadbs/tcod, they get a link to the appropriate links endpoint. This has come up a few times in tutorials and other issues (#75, https://github.com/Materials-Consortia/providers-dashboard/issues/60 and https://github.com/Materials-Consortia/providers/pull/74#issuecomment-917536479)

**Comment by ml-evs** [comment]
The other option would be to redirect all "raw" base URLs to the appropriate links endpoint.

**Comment by CasperWA** [comment]
> The other option would be to redirect all "raw" base URLs to the appropriate links endpoint.

I see you've already implemented this in #77, but I'm not sure this is the "correct" way to handle this. However, it is convenient. Personally, I'd prefer a web page response, as I may be a confused client going to the base URL and suddenly be redirected to a functional entry endpoint - it seems off, but it's very practical.

**Comment by ml-evs** [comment]
We can change my redirects to instead serve a custom 404 page (for just the providers base URLs), but what info should be on it? We can't use a templating engine or anything, so I don't think we can provide a link to the links endpoint, or serve any provider-specific data as we do in the OPT landing page (unless there are some HTML-only hacks for relative redirects/getting the current requested URL).

**Comment by CasperWA** [comment]
I would just add some hard-coded "common shortcomings/mistakes" list with a mention of "did you remember to add the major version and endpoint to the path?" or something?

**Comment by ml-evs** [comment]
Have updated my PR with something along these lines.

**Comment by ml-evs** [comment]
Closed by #77
