### ISSUE TITLE
Should the base URL include /optimade/ ?

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/providers#8]
I am wondering whether or not we need to be 100 % stringent with this index meta-database. If yes, the base URL should contain `/optimade/` I guess, e.g., https://www.optimade.org/providers/optimade/links or https://www.optimade.org/optimade/links

**Comment by ltalirz** [comment]
I don't think the base URL needs to contain `/optimade/`.
See valid examples in https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#id5

**Comment by ltalirz** [comment]
Ah, perhaps I misunderstood.
If the server responds under  <url>/optimade, then I think the full <url>/optimade should be reported here.

**Comment by rartino** [comment]
I don't understand. Presently the base url to the top index meta-database is:
- https://www.optimade.org/providers/

The links endpoint, for example, is at
- https://www.optimade.org/providers/links

Is the suggestion in this issue to move it?, e.g., to:
- https://www.optimade.org/providers/optimade

Why?

I have proposed elsewhere (Materials-Consortia/OPTiMaDe#236) that we should move it to:
- https://providers.optimade.org/

The motivation is that this would allow its hosting to be changed completely independently of our website. But that would still be without an `optimade` suffix, which I don't see the use for here.

**Comment by CasperWA** [comment]
Closing this, since the concept of base URLs (specifically _versioned_ base URLs) has been resolved with Materials-Consortia/OPTiMaDe#240.
